#!/bin/bash
mongosh
show dbs
use Loc8r 
db.locations.insertOne({
	name: 'Starcups',
	address: '125 High Street, Reading, RG6 1PS',
	rating: 3,
	facilities: ['Hot drinks', 'Food', 'Premium wifi'],
	coords: [-0.9690884, 51.455041],
	openingTimes: [{
	days: 'Monday - Friday',
	opening: '7:00am',
	closing: '7:00pm',
	closed: false
	}, 
	{
	days: 'Saturday',
	opening: '8:00am',
	closing: '5:00pm',
	closed: false
	}, 
	{
	days: 'Sunday',
	closed: true
	}]
})


db.locations.insertOne({
	name: 'Taberna Entrevinos',
	address: 'Calle Francisco Gongora, 11',
	rating: 4,
	facilities: ['Hot drinks', 'Food', 'Premium wifi'],
	coords: [-2.4500605, 36.8388697],
	openingTimes: [{
	days: 'Monday - Friday',
	opening: '7:00am',
	closing: '7:00pm',
	closed: false
	}, 
	{
	days: 'Saturday',
	opening: '8:00am',
	closing: '5:00pm',
	closed: false
	}, 
	{
	days: 'Sunday',
	closed: true
	}]
})

db.locations.insertOne({
	name: 'Restaurante Valentin',
	address: 'Calle Tenor Iribarne, 19',
	rating: 4,
	facilities: ['Hot drinks', 'Food', 'Premium wifi'],
	coords: [-2.4649475, 36.8412037],
	openingTimes: [{
	days: 'Monday - Friday',
	opening: '7:00am',
	closing: '7:00pm',
	closed: false
	}, 
	{
	days: 'Saturday',
	opening: '8:00am',
	closing: '5:00pm',
	closed: false
	}, 
	{
	days: 'Sunday',
	closed: true
	}]
})

db.locations.updateOne({
	name: 'Starcups'
	}, {
	$push: {
		reviews: {
			author: 'Simon Holmes',
			_id: ObjectId(),
			rating: 5,
			timestamp: new Date("Jul 16, 2013"),
			reviewText: "What a great place. I can't say enough good things about it."
			}
	}
})